### ISSUE TITLE
Horizons in RiskEstimationStudy

### ISSUE THREAD

**Issue by 11Dmitriy11** [vanderschaarlab/autoprognosis#82]
## Question
Hello! It is suggested that we put set a particular horizons in RiskEstimationStudy. Could you please explain why this is necessary?
Does this reduce the time for calculating the risk function due to its approximation on intervals?
At the same time, we can specify any horizons in predict function

**Comment by DrShushen** [comment]
The time horizons at `fit` time are needed because they affect the model selection. In order to perform model selection, the survival performance metrics need to be computed (so that better performing models can be automatically selected). These are computed at the time horizons you provide.
At `predict` time you can select different time horizons.
